name: verify

on:
  push:
  pull_request:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v2.4.0
      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v2.2.0
        with:
          go-version: 1.19
          check-latest: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@639cd343e1d3b897ff35927a75193d57cfcba299 # v3.1.0
        timeout-minutes: 5
        with:
          version: v1.49.0

      - run: |
          go mod tidy
          git diff --exit-code
